name: Smoke test

on: pull_request

jobs:
  flagsmith:
    runs-on: ubuntu-latest
    environment: test
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./
        with:
          api-url: https://api-staging.flagsmith.com
      - run: flagsmith --version
      - run: flagsmith flag list --project "Edge API E2E" -e E2E
